use promhttp as prometheus.Handler is deprecated
go build failed with: 

./bash-exporter.go:58:26: undefined: prometheus.Handler

prometheus.Handler seems to be deprecated. replaced with promhttp.Handler